### ISSUE TITLE
Fatal Error when trying to open new panel

### ISSUE THREAD

**Issue by samrshi** [TheCJGCJG/CJFreedom-Panel#1]
This is the error I get when I try to open the new panel "Fatal error: Cannot redeclare encrypt() (previously declared in /var/www/html/thecjgcjg.com/cjfreedom/panel/inc/functions.php:2) in /var/www/html/thecjgcjg.com/cjfreedom/panel/inc/functions.php on line 8" (https://thecjgcjg.com/cjfreedom/panel/)

**Comment by TheCJGCJG** [comment]
Error should have been fixed

https://github.com/TheCJGCJG/CJFreedom-Panel/commit/ca54e6944689c8073c9cd4ac586b7de65c030af2

**Comment by samrshi** [comment]
It has been fixed, thank you
